#pragma once

#include "CoreMinimal.h"
#include "PCGSettings.h"
#include "PCGData.h"
#include "UPCGCreatePointsManhattan.generated.h"

/**
 * @brief Structure defining Manhattan offset parameters for creating a new point.
 */
USTRUCT(BlueprintType)
struct FPCGPointManhattanOffsetToCreate
{
	GENERATED_BODY()

	/** X offset from the original point. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Settings")
	float XOffset = 0.f;

	/** Y offset from the original point. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Settings")
	float YOffset = 0.f;

	/** Additional yaw (in degrees) to add to the original point's rotation. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Settings")
	float PointAddedYaw = 0.f;

	// to optionally add z to the final position of the point.
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Settings")
	float ZOffset = 0.f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Settings")
	FVector Bounds = FVector(100.f, 100.f, 100.f);
	
};

/**
 * @brief PCG node for creating points with Manhattan offsets.
 *
 * This node creates new points by adding defined X and Y offsets to each input point's location.
 * The node also optionally adjusts the point rotation by adding a yaw value.
 */
UCLASS(BlueprintType)
class RTS_SURVIVAL_API UPCGCreatePointsManhattan : public UPCGSettings
{
	GENERATED_BODY()

public:
	/** Array of Manhattan offset definitions used to generate new points from the input points. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Settings")
	TArray<FPCGPointManhattanOffsetToCreate> PointsToCreate;

	// ~Begin UPCGSettings interface
#if WITH_EDITOR
	/**
	 * @brief Returns the default node name.
	 * @return FName representing the node name.
	 */
	virtual FName GetDefaultNodeName() const override { return FName(TEXT("CreatePointsManhattan")); }

	/**
	 * @brief Returns the node title.
	 * @return FText representing the node title.
	 */
	virtual FText GetDefaultNodeTitle() const override { return FText::FromString(TEXT("Create Points Manhattan")); }

	/**
	 * @brief Returns the tooltip text for this node.
	 * @return FText representing the tooltip.
	 */
	virtual FText GetNodeTooltipText() const override { return FText::FromString(TEXT("Creates points with Manhattan offsets from the input points.")); }

	/**
	 * @brief Returns the type of PCG settings.
	 * @return EPCGSettingsType indicating that this is a sampler node.
	 */
	virtual EPCGSettingsType GetType() const override { return EPCGSettingsType::Sampler; }
#endif

	/**
	 * @brief Indicates whether this node uses a seed.
	 * @return true if a seed is used.
	 */
	virtual bool UseSeed() const override { return true; }

	/**
	 * @brief Indicates whether this node has dynamic pins.
	 * @return true if dynamic pins are present.
	 */
	virtual bool HasDynamicPins() const override { return true; }
protected:
	/**
	 * @brief Returns the properties for the input pins.
	 * @return An array of FPCGPinProperties defining the input pins.
	 */
	virtual TArray<FPCGPinProperties> InputPinProperties() const override;

	/**
	 * @brief Returns the properties for the output pins.
	 * @return An array of FPCGPinProperties defining the output pins.
	 */
	virtual TArray<FPCGPinProperties> OutputPinProperties() const override;

	/**
	 * @brief Creates the PCG element that executes the node’s logic.
	 * @return A shared pointer to the created IPCGElement.
	 */
	virtual FPCGElementPtr CreateElement() const override;
	// ~End UPCGSettings interface
};

/**
 * @brief PCG element that executes the Manhattan offset creation.
 */
class FPCGCreatePointsManhattanElement : public IPCGElement
{
protected:
	/**
	 * @brief Executes the Manhattan point creation.
	 *
	 * For each input point, new points are generated by adding the specified X and Y offsets.
	 * The yaw rotation of each new point is also adjusted by the provided PointAddedYaw value.
	 *
	 * @param Context The PCG context containing input and output data.
	 * @return true if execution was successful; false otherwise.
	 */
	virtual bool ExecuteInternal(FPCGContext* Context) const override;
};
